[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCodeNerdFont"
style = "Bold"

[font.bold_italic]
family = "FiraCodeNerdFont"
style = "Bold Italic"

[font.italic]
family = "FiraCodeNerdFont"
style = "Italic"

[font.normal]
family = "FiraCodeNerdFont"
style = "Regular"

[window]
# turned off since transparency is managed by picom compostion manager
opacity = 0.85

[colors.primary]
background = "#1a1c23"

[colors.selection]
background = "#a2c7e8"

[colors.cursor]
text = "#303446"
cursor = "#c8e8fa"
